### ISSUE TITLE
[prerender-fargate] limit domain name

### ISSUE THREAD

**Issue by crispy101** [aligent/cdk-constructs#890]
Issue: Working even with an arbitrary host header, e.g.:
```
curl -i -sk -H "x-prerender-token: <REDACTED>"  -H "Host: RANDOM.DOMAIN" https://ALB-URL/render?url=https://REAL.DOMAIN/
```

Expect to work: return 401 to requests with a wrong host header

**Comment by TheOrangePuff** [comment]
@crispy101 I think this is no longer valid? Feel free to re-open an internal ticket if it is.
