### ISSUE TITLE
CSP not optional

### ISSUE THREAD

**Issue by crispy101** [aligent/cdk-constructs#938]
Fails to deploy with the error below when CSP is not provided, even though it is optional:

> Resource handler returned message: "Invalid request provided: AWS::CloudFront::ResponseHeadersPolicy: The parameter Content-Security-Policy contains header value that is too small or empty. (Service: CloudFront, Status Code: 400, ...)

Tested version: 0.1.13

**Comment by TheOrangePuff** [comment]
@crispy101 I believe this is resolved. Can you confirm?
